### ISSUE TITLE
ACME EXAMPLE DOESN'T WORK

### ISSUE THREAD

**Issue by gabryk9** [RealTimeLogic/LspAppMgr-ESP32#1]
The URL returned by the acme.lsp example is a domain not found
![Schermata da 2020-11-16 11-10-07](https://user-images.githubusercontent.com/48953262/99240150-5cf90e80-27fc-11eb-88bb-54b75b65dcc1.png)
![Schermata da 2020-11-16 11-10-12](https://user-images.githubusercontent.com/48953262/99240178-65e9e000-27fc-11eb-9ea3-552e559e5f89.png)

**Comment by surfskidude** [comment]
I believe this has been fixed
